const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";
const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";
const FETCH_EMPLOYEE_REQUEST_SAGA = "FETCH_EMPLOYEE_REQUEST_SAGA";

const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";
const ADD_EMPLOYEE_REQUEST_SAGA = "ADD_EMPLOYEE_REQUEST_SAGA";

const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";
const UPDATE_EMPLOYEE_REQUEST_SAGA = "UPDATE_EMPLOYEE_REQUEST_SAGA";

const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";
const DELETE_EMPLOYEE_REQUEST_SAGA = "DELETE_EMPLOYEE_REQUEST_SAGA";

export {
    FETCH_EMPLOYEE_REQUEST,
    FETCH_EMPLOYEE_SUCCESS,
    FETCH_EMPLOYEE_FAILURE,
    FETCH_EMPLOYEE_REQUEST_SAGA,
    //
    ADD_EMPLOYEE_REQUEST,
    ADD_EMPLOYEE_SUCCESS,
    ADD_EMPLOYEE_FAILURE,
    ADD_EMPLOYEE_REQUEST_SAGA,
    //
    UPDATE_EMPLOYEE_REQUEST,
    UPDATE_EMPLOYEE_SUCCESS,
    UPDATE_EMPLOYEE_FAILURE,
    UPDATE_EMPLOYEE_REQUEST_SAGA,
    //
    DELETE_EMPLOYEE_REQUEST,
    DELETE_EMPLOYEE_SUCCESS,
    DELETE_EMPLOYEE_FAILURE,
    DELETE_EMPLOYEE_REQUEST_SAGA,
};
