const FETCH_EMPLOYEE_REQUEST = "FETCH_EMPLOYEE_REQUEST";
const FETCH_EMPLOYEE_SUCCESS = "FETCH_EMPLOYEE_SUCCESS";
const FETCH_EMPLOYEE_FAILURE = "FETCH_EMPLOYEE_FAILURE";
const FETCH_EMPLOYEE_REQUEST_NO_SAGA = "FETCH_EMPLOYEE_REQUEST_NO_SAGA";

export {
    FETCH_EMPLOYEE_REQUEST,
    FETCH_EMPLOYEE_SUCCESS,
    FETCH_EMPLOYEE_FAILURE,
    FETCH_EMPLOYEE_REQUEST_NO_SAGA,
};
